# Use postgres/example user/password credentials
version: '3.1'

services:
  app:
    build: .
    command: python3 etl.py
    environment:
      DB_URL: postgresql://postgres:postgres@database:5432/postgres
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge